# Generated by Django 5.2.17 on 2026-09-23 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('roteiro', 'Roteiro'), ('video', 'Vídeo')], max_length=10)),
                ('status', models.CharField(choices=[('fila', 'Na fila'), ('rodando', 'Rodando'), ('ok', 'Pronto'), ('erro', 'Erro')], default='fila', max_length=10)),
                ('etapa', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('entrada', models.JSONField(default=dict)),
                ('saida', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
        ),
    ]
