# Generated by Django 5.2.17 on 2026-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
