# Generated by Django 5.2.17 on 2026-09-24 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_custos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('nicho', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=False)),
                ('meta_dia', models.PositiveSmallIntegerField(default=3)),
                ('musica', models.CharField(default='ambas', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pausado', models.BooleanField(default=False)),
                ('intervalo_min', models.PositiveSmallIntegerField(default=20)),
                ('batimento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicho', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=30)),
                ('formato_nome', models.CharField(blank=True, max_length=80)),
                ('titulo', models.CharField(max_length=200)),
                ('tema_id', models.CharField(blank=True, max_length=60)),
                ('origem', models.CharField(default='catalogo', max_length=10)),
                ('prioridade', models.SmallIntegerField(default=1)),
                ('usado', models.BooleanField(default=False)),
                ('falhas', models.PositiveSmallIntegerField(default=0)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prioridade', 'criado'],
                'constraints': [models.UniqueConstraint(fields=('nicho', 'formato', 'titulo'), name='pauta_unica')],
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nicho', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=30)),
                ('tema', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('fila', 'Na fila'), ('gerando', 'Gerando'), ('revisar', 'Para revisar'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('postado', 'Postado'), ('falhou', 'Falhou')], default='fila', max_length=10)),
                ('etapa', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('log', models.TextField(blank=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('post', models.TextField(blank=True)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('custos', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('postado_youtube', models.DateTimeField(blank=True, null=True)),
                ('postado_tiktok', models.DateTimeField(blank=True, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('iniciado', models.DateTimeField(blank=True, null=True)),
                ('terminado', models.DateTimeField(blank=True, null=True)),
                ('pauta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudio.pauta')),
            ],
            options={
                'ordering': ['-criado'],
            },
        ),
    ]
