# Generated by Django 5.2.17 on 2026-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_canal_produtor_pauta_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='musica',
            field=models.CharField(default='sem', max_length=5),
        ),
    ]
