# Generated by Django 5.2.17 on 2026-09-24 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudio", "0004_um_video_so"),
    ]

    operations = [
        migrations.AddField(
            model_name="canal",
            name="modo",
            field=models.CharField(default="unitario", max_length=10),
        ),
        migrations.AddField(
            model_name="canal",
            name="serie_cada",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="canal",
            name="serie_max",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="producao",
            name="parte",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nicho", models.CharField(max_length=20)),
                ("formato", models.CharField(max_length=30)),
                ("tema", models.CharField(max_length=200)),
                ("max_partes", models.PositiveSmallIntegerField(default=3)),
                ("automatica", models.BooleanField(default=False)),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("plano", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="fila", max_length=10)),
                ("etapa", models.CharField(blank=True, max_length=20)),
                ("mensagem", models.CharField(blank=True, max_length=300)),
                ("avisos", models.JSONField(blank=True, default=list)),
                ("log", models.TextField(blank=True)),
                ("custos", models.JSONField(blank=True, default=dict)),
                ("erro", models.TextField(blank=True)),
                ("motivo", models.CharField(blank=True, max_length=300)),
                ("criado", models.DateTimeField(auto_now_add=True)),
                ("iniciado", models.DateTimeField(blank=True, null=True)),
                ("terminado", models.DateTimeField(blank=True, null=True)),
                (
                    "pauta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estudio.pauta",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado"],
            },
        ),
        migrations.AddField(
            model_name="producao",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partes",
                to="estudio.serie",
            ),
        ),
    ]
