# Generated by Django 5.2.17 on 2026-09-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_um_video_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='imagens',
            field=models.CharField(default='ia', max_length=10),
        ),
    ]
