# Generated by Django 5.2.17 on 2026-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_imagens_nativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='cancelar',
            field=models.BooleanField(default=False),
        ),
    ]
