# Generated by Django 5.2.17 on 2026-09-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0007_produtor_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='avisos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='produtor',
            name='falhas_zeradas_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
