# Generated by Django 5.2.17 on 2026-09-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_series'),
        ('estudio', '0008_avisos_e_zerar'),
    ]

    operations = [
    ]
