# Generated by Django 5.2.17 on 2026-09-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0009_merge_0005_series_0008_avisos_e_zerar'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='efeitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canal',
            name='legenda',
            field=models.CharField(default='padrao', max_length=12),
        ),
        migrations.AddField(
            model_name='canal',
            name='volume',
            field=models.BooleanField(default=False),
        ),
    ]
