# Generated by Django 5.2.17 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0010_opcoes_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='voz',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
