# Generated by Django 5.2.17 on 2026-09-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0011_voz_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='estilo_pod',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='canal',
            name='roteiro',
            field=models.CharField(default='padrao', max_length=10),
        ),
    ]
